
package cn.ac.ia.cip.utils.mt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "STMTWebService", targetNamespace = "http://webservices.mt.nlp.istic.ac.cn/", wsdlLocation = "http://mt.istic.ac.cn:8080/stmtservice/STMTWebPort?wsdl")
public class STMTWebService
    extends Service
{

    private final static URL STMTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException STMTWEBSERVICE_EXCEPTION;
    private final static QName STMTWEBSERVICE_QNAME = new QName("http://webservices.mt.nlp.istic.ac.cn/", "STMTWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://mt.istic.ac.cn:8080/stmtservice/STMTWebPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STMTWEBSERVICE_WSDL_LOCATION = url;
        STMTWEBSERVICE_EXCEPTION = e;
    }

    public STMTWebService() {
        super(__getWsdlLocation(), STMTWEBSERVICE_QNAME);
    }

    public STMTWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STMTWEBSERVICE_QNAME, features);
    }

    public STMTWebService(URL wsdlLocation) {
        super(wsdlLocation, STMTWEBSERVICE_QNAME);
    }

    public STMTWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STMTWEBSERVICE_QNAME, features);
    }

    public STMTWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public STMTWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns STMTWeb
     */
    @WebEndpoint(name = "STMTWebPort")
    public STMTWeb getSTMTWebPort() {
        return super.getPort(new QName("http://webservices.mt.nlp.istic.ac.cn/", "STMTWebPort"), STMTWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns STMTWeb
     */
    @WebEndpoint(name = "STMTWebPort")
    public STMTWeb getSTMTWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.mt.nlp.istic.ac.cn/", "STMTWebPort"), STMTWeb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STMTWEBSERVICE_EXCEPTION!= null) {
            throw STMTWEBSERVICE_EXCEPTION;
        }
        return STMTWEBSERVICE_WSDL_LOCATION;
    }

}
